### ISSUE TITLE
Missing lorenzFun and missing addpath in lorenzExample.m

### ISSUE THREAD

**Issue by sgrine** [baddoo/LANDO#1]
addpath('../src')

>> lorenzExample
Unrecognized function or variable 'lorenzFun'.
Error in lorenzExample>@(t,x)lorenzFun(t,x,Sigma,Beta,rho) (line 15)
[t,x]=ode45(@(t,x) lorenzFun(t,x,Sigma,Beta,rho),tspan,x0,options); % Generate data
Error in odearguments (line 90)
f0 = feval(ode,t0,y0,args{:});   % ODE15I sets args{1} to yp0.
Error in ode45 (line 115)
  odearguments(FcnHandlesUsed, solver_name, ode, tspan, y0, options, varargin);
Error in lorenzExample (line 15)
[t,x]=ode45(@(t,x) lorenzFun(t,x,Sigma,Beta,rho),tspan,x0,options); % Generate data

**Comment by baddoo** [comment]
Thanks for spotting this, it should be fixed now!
