### ISSUE TITLE
Unrecognized function or variable 'color_line3'.

### ISSUE THREAD

**Issue by sgrine** [baddoo/LANDO#2]
When running: lorenzTVDiffKRLS.m

Unrecognized function or variable 'color_line3'.

Error in lorenzTVDiffKRLS (line 93)
color_line3(xCPlot(:,1),xCPlot(:,2),xCPlot(:,3),[0;
diff(tPlot)],LW,1);

**Comment by baddoo** [comment]
Fixed, thanks for flagging this.
